### ISSUE TITLE
Make the form functional

### ISSUE THREAD

**Issue by kmal808** [kmal808/table-7#5]
Connect the form to whatever email is decided upon by the group.

**Comment by leroialfonse** [comment]
I'm pretty sure I can do that, but I'm new to contributions. Can I be assigned to this ?

**Comment by kmal808** [comment]
Sorry was at work all day, I see your PR so it looks like there is no need to assign the issue. How did you find this repo/issue if you don't mind me asking? We built this repo to help people(preferably fellow 100Devs like yourself) get comfortable in the GitHub workflow, so I'm glad you were able to find us if you'd like to join our study group jump aboard.

**Comment by kmal808** [comment]
PR Merged

**Comment by leroialfonse** [comment]
Hey, no worries, fam. We've all gotta pay bills and such.

I was looking around through "Good First Issues" via "First Timers Only"
This Issue was on page 3 or 4 after specifically narrowing search criteria
to HTML, CSS, and JavaScript issues.

When I noticed it was a 100Devs repo, I was like, "Aha, cool!"
It definitely seems to have helped me get a little more comfortable with
GitHub workflow, as evidenced by my apparent success in committing!

I should definitely start making inroads into participating in some kind of
study group; been a little tougher than necessary going it alone.
How/where do you guys meet?

**Comment by kmal808** [comment]
We just started it last week and haven't met yet, so you'd be coming in at a great time. We'll be meeting via zoom or similar since we're scattered across the western hemisphere. Hmu on Twitter https://twitter.com/kmal808

**Comment by leroialfonse** [comment]
Excellent.
